In [1]:
import numpy as np

# Sigmoid function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


# -----------------------------
# Given values
# -----------------------------

X = np.array([[1.0],
              [0.0]])

y = 1.0

# Input -> Hidden weights
W1 = np.array([
    [0.2, 0.3],
    [0.4, 0.1]
])

# Hidden -> Output weights
W2 = np.array([
    [0.5],
    [0.6]
])

# Learning rate
learning_rate = 0.1


# -----------------------------
# Forward Propagation
# -----------------------------

# Hidden layer
Z1 = W1.T @ X
H = sigmoid(Z1)

# Output layer
Z2 = W2.T @ H
y_pred = sigmoid(Z2)

# MSE loss with 1/2 factor
loss = 0.5 * (y - y_pred[0, 0]) ** 2


print("Forward Propagation")
print("-------------------")

print("Z1:")
print(Z1)

print("\nHidden activations H:")
print(H)

print("\nZ2:")
print(Z2)

print("\nOutput prediction:")
print(y_pred)

print("\nLoss:")
print(loss)


# -----------------------------
# Backpropagation
# -----------------------------

# Output layer error
delta2 = (y_pred - y) * y_pred * (1 - y_pred)

# Gradient of W2
dW2 = H @ delta2.T

# Hidden layer error
delta1 = (W2 * delta2) * H * (1 - H)

# Gradient of W1
dW1 = X @ delta1.T


print("\nBackpropagation")
print("----------------")

print("delta2:")
print(delta2)

print("\ndW2:")
print(dW2)

print("\ndelta1:")
print(delta1)

print("\ndW1:")
print(dW1)


# -----------------------------
# Weight Updates
# -----------------------------

W1_new = W1 - learning_rate * dW1
W2_new = W2 - learning_rate * dW2


print("\nUpdated Weights")
print("----------------")

print("Updated W1:")
print(W1_new)

print("\nUpdated W2:")
print(W2_new)


# -----------------------------
# Verify with Updated Weights
# -----------------------------

Z1_new = W1_new.T @ X
H_new = sigmoid(Z1_new)

Z2_new = W2_new.T @ H_new
y_pred_new = sigmoid(Z2_new)

loss_new = 0.5 * (y - y_pred_new[0, 0]) ** 2


print("\nAfter Weight Update")
print("-------------------")

print("New hidden activations:")
print(H_new)

print("\nNew prediction:")
print(y_pred_new)

print("\nNew loss:")
print(loss_new)

Forward Propagation
-------------------
Z1:
[[0.2]
 [0.3]]

Hidden activations H:
[[0.549834  ]
 [0.57444252]]

Z2:
[[0.61958251]]

Output prediction:
[[0.65012359]]

Loss:
0.06120675087427858

Backpropagation
----------------
delta2:
[[-0.07958391]]

dW2:
[[-0.04375794]
 [-0.04571638]]

delta1:
[[-0.00984917]
 [-0.01167297]]

dW1:
[[-0.00984917 -0.01167297]
 [ 0.          0.        ]]

Updated Weights
----------------
Updated W1:
[[0.20098492 0.3011673 ]
 [0.4        0.1       ]]

Updated W2:
[[0.50437579]
 [0.60457164]]

After Weight Update
-------------------
New hidden activations:
[[0.55007777]
 [0.57472785]]

New prediction:
[[0.65133444]]

New loss:
0.06078383588351899
